name: PHP Composer Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app

    - name: Setup PHP & PHPUnit
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Code analysis
      run: vendor/bin/phpstan analyse

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app

    - name: Deploy to staging
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /var/www/staging
        remote_host: ${{ secrets.STAGING_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}

    - name: Manual approval
      uses: actions/manual-trigger@v1

    - name: Deploy to production
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /var/www/production
        remote_host: ${{ secrets.PRODUCTION_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
